#!/bin/bash

(
SOURCE_DIR="$(readlink -f $(dirname $0))"
BUILD_DIR="$(dirname ${SOURCE_DIR})/app-build"
INSTALL_DIR="$(dirname ${SOURCE_DIR})/app-install"
mkdir -p $BUILD_DIR $INSTALL_DIR
cd $BUILD_DIR

cmake -G Ninja \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX="${INSTALL_DIR}" \
    -DCMAKE_PREFIX_PATH="$(dirname ${SOURCE_DIR})/install" \
    "${SOURCE_DIR}"
ninja -j $(nproc) install
)
