#!/bin/bash

(
build_type=${1:-Release}
SOURCE_DIR="$(readlink -f $(dirname $0))"
BUILD_DIR="$(dirname ${SOURCE_DIR})/app-build"
INSTALL_DIR="$(dirname ${SOURCE_DIR})/app-install"
mkdir -p $BUILD_DIR $INSTALL_DIR

cd $BUILD_DIR

cmake -G Ninja \
    -DCMAKE_BUILD_TYPE=${build_type} \
    -DCMAKE_INSTALL_PREFIX="${INSTALL_DIR}" \
    -DCMAKE_PREFIX_PATH="$(dirname ${SOURCE_DIR})/install" \
    -DCMAKE_INSTALL_RPATH="$(readlink -f ${SOURCE_DIR}/../install/lib)" \
    "${SOURCE_DIR}"
ninja -j $(nproc) install
)
